
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkmnuyqgllnaiqiotsoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbW51eXFnbGxuYWlxaW90c296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTEyMDksImV4cCI6MjA2MTA2NzIwOX0.-cU_cLNIX5Ld8Tjvw7SeFPtyNFArn8qu45Nppl5Ibj4";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    }
  }
});
